server:
  port: 8088
spring:
  datasource:
    url: jdbc:postgresql://database-1.ciqbwacxdcmc.us-east-1.rds.amazonaws.com:5432/postgres
    username: postgres
    password: password#1
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    show-sql: false
    hibernate.ddl-auto: create-drop
  batch:
    initialize-schema: always
    job.enabled: false